parameters:
  name: ""
  pipelineBuildImage: "containernetworking/pipeline-ci:1.0.4"
  testClusterDefinitionUrl: "https://raw.githubusercontent.com/Azure/azure-container-networking/master/test/e2e/kubernetes/cniLinux.json"

jobs:
  - job: ${{ parameters.name }}
    dependsOn: Unit_Tests
    pool:
      name: Networking-ContainerNetworking
      demands: agent.os -equals Linux
    container:
      image: ${{ parameters.pipelineBuildImage }}
    variables:
      GOPATH: "$(System.DefaultWorkingDirectory)/gopath"
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/aks-engine"
      Tag: $[ dependencies.Unit_Tests.outputs['EnvironmentalVariables.Tag'] ]
      CommitHash: $[ dependencies.Unit_Tests.outputs['EnvironmentalVariables.CommitHash'] ]

    steps:
      - template: e2e-step-template.yaml
        parameters:
          testClusterDefinitionUrl: ${{ parameters.testClusterDefinitionUrl }}
